config/routes.rb
Rails.application.routes.draw do

  root 'landing#user'

  devise_for :users,
             :controllers => {
                sessions: 'sessions', registrations: 'registrations'
             }

  get 'landing/terms_of_use'
  get 'landing/privacy_policy'
  get 'landing/cookie_policy'
  get 'landing/usage_agreement'
  get 'landing/the_kitchen_economy'
  get 'landing/help'

  get 'dashboard' => 'account#show'
  post 'account/payment'

  get 'search/results'
  post 'kitchen/create'

  resources :kitchen do
    match "reservation/new" => "reservation#new", via: :post
    resources :reservation, only: [:create, :show]
    resources :availability, only: :create
  end

  resources :reservation, only: [:edit, :update, :destroy]
  resources :availability, only: [:new, :show, :edit, :update, :destroy]

  scope '/api' do
    scope '/v1' do
      get '/kitchens' => 'kitchen#filter'
    end
  end

  resources :conversations, only: [:index, :destroy] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    member do
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def reply
    text = params[:body]

    if text.downcase.match(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/).present?
      message_error = 'Error: Message includes an email.'
      flash[:notice] = message_error
      redirect_to request.referer
    elsif contains_valid_phone_number(text)
      message_error = 'Error: Message includes a phone number.'
      flash[:notice] = message_error
      redirect_to request.referer
    else
      current_user.reply_to_conversation(@conversation, text)
      redirect_to conversation_path(@conversation)
    end
  end

  def destroy
    @conversation.move_to_trash(current_user)
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    redirect_to conversations_path
  end

  def show
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def contains_valid_phone_number(text)
    country_code = "44"
    # Get potential phone numbers from text
    numbers = text.upcase.scan(/([^A-Z|^"]{6,})/i).collect{|x| x[0].strip }
    # Check if any of the gathered numbers is a possible phone number in the given country
    return numbers.any? { |n| plausible_phone_number(n) || plausible_phone_number(country_code+n) }
  end

  def plausible_phone_number(number)
    Phony.plausible?(number.gsub(/[^0-9]/i, ''))
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/index.html.erb
<body class="mailbox-body">
  <%= render("shared/menu") %>

  <div class="mailbox-menu">
    <ul class="mailbox-menu-list">
      <li class="mailbox-menu-list-el">
        <%= mailbox_section 'inbox', @box %>
      </li>
      <li class="mailbox-menu-list-el">
        <%= mailbox_section 'sent', @box %>
      </li>
      <!-- <li class="mailbox-menu-list-el">
        <%# mailbox_section 'trash', @box %>
      </li> -->
    </ul>
  </div>

  <div class="mailbox-message-container">
    <% if @box == 'trash' %>
      <p><%= button_to 'Empty trash', empty_trash_conversations_path, method: :delete, data: {confirm: 'Are you sure?'} %></p>
    <% end %>
    <ul class="mailbox-message-list">
      <% @conversations.each do |conversation| %>
        <li class="mailbox-message-list-el">
          <%= conversation.subject %>
          <!-- <div class="pull-right">
            <% if conversation.is_trashed?(current_user) %>
              <%= button_to 'Restore', restore_conversation_path(conversation), method: :post %>
            <% else %>
              <%= button_to 'Move to trash', conversation_path(conversation), method: :delete, data: {confirm: 'Are you sure?'} %>
              <% if conversation.is_unread?(current_user) %>
                <%= button_to 'Mark as read', mark_as_read_conversation_path(conversation), method: :post %>
              <% end %>
            <% end %>
          </div> -->
          <% conversation.receipts_for(current_user).each do |receipt| %>
            <% message = receipt.message %>
            <div class="pull-right">
              <%= message.created_at.strftime("%B %-d, %H:%M") %>
            </div>
            <br>
            <p>
              From: <%= message.sender.first_name %>
            </p>
            <p>
              Message: <%= message.body %>
            </p>
          <% end %>
          <br/>
          <%= form_tag reply_conversation_path(conversation), method: :post do %>
            <div>
              <%= text_area_tag 'body', nil, cols: 50, class: 'form-control', placeholder: 'Type something...', required: true %>
            </div>
            <%= submit_tag "Reply" %>
          <% end %>
        </li>
        <br/>
      <% end %>
    </ul>
  </div>

  <%# will_paginate %>
  <%= render("shared/footer") %>
</body>

app/views/conversations/show.html.erb
<body>
  <%= render("shared/menu") %>

  <p>Conversation Subject:<br>
    <%= @conversation.subject %>
  </p>

  <% @conversation.receipts_for(current_user).each do |receipt| %>
    <% message = receipt.message %>

    <br>
    <p>From:<br>
      <%= message.sender.first_name %>
    </p>

    <br>
    <p>Message:<br>
      <%= message.body %>
    </p>

    <br>
    <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %>
  <% end %>

  <br>
  <br>
  <br>

  <%= form_tag reply_conversation_path(@conversation), method: :post do %>
    <div>
      <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
    </div>
    <%= submit_tag "Reply" %>
  <% end %>

</body>