config/routes.rb
Rails.application.routes.draw do

  root 'landing#user'

  devise_for :users,
             :controllers => {
                sessions: 'sessions', registrations: 'registrations'
             }

  get 'landing/terms_of_use'
  get 'landing/privacy_policy'
  get 'landing/cookie_policy'
  get 'landing/usage_agreement'
  get 'landing/the_kitchen_economy'
  get 'landing/help'

  get 'dashboard' => 'account#show'
  post 'account/payment'

  get 'search/results'
  post 'kitchen/create'

  resources :kitchen do
    match "reservation/new" => "reservation#new", via: :post
    resources :reservation, only: [:create, :show]
    resources :availability, only: :create
  end

  resources :reservation, only: [:edit, :update, :destroy]
  resources :availability, only: [:new, :show, :edit, :update, :destroy]

  scope '/api' do
    scope '/v1' do
      get '/kitchens' => 'kitchen#filter'
    end
  end

  resources :conversations, only: [:index, :destroy] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    member do
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

end

app/views/shared/_footer.html.erb
<footer class="footer-distributed">
  <div class="footer-left">
    <ul class="footer-links">
      <li class="footer-link-list-element"><%= link_to "The Kitchen Economy", landing_the_kitchen_economy_path %></li>
      <li class="footer-link-list-element"><%= link_to "Terms of Use", landing_terms_of_use_path %></li>
      <li class="footer-link-list-element"><%= link_to "Privacy Policy", landing_privacy_policy_path %></li>
      <li class="footer-link-list-element"><%= link_to "Cookie Policy", landing_cookie_policy_path %></li>
    </ul>
    <p class="footer-company-name">Share Dining Limited © 2016</p>
  </div>

  <div class="footer-center">
    <div>
      <i class="fa fa-phone"></i>
      <p>+44 7713 147510</p>
    </div>
    <div>
      <i class="fa fa-envelope"></i>
      <p><a href="mailto:support@sharedining.co.uk">support@sharedining.co.uk</a></p>
    </div>
  </div>

  <div class="footer-right">
    <p class="footer-company-about">
      <span>Creating the kitchen economy</span>
    </p>

    <ul class="footer-icons">
      <li class="footer-icon-list-element">
        <a href="https://www.facebook.com/sharediningltd/?fref=ts" target="_blank"><i class="fa fa-facebook"></i></a>
      </li>
      <li class="footer-icon-list-element">
        <a href="https://twitter.com/ShareDiningHQ" target="_blank"><i class="fa fa-twitter"></i></a>
      </li>
      <li class="footer-icon-list-element">
        <a href="https://www.instagram.com/sharedining/" target="_blank"><i class="fa fa-instagram"></i></a>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_menu.html.erb
<!--we should render this on everypage and simply link to the icons via use-->
<%= render 'shared/icons' %>
<nav class="main-nav">
  <a class="main-logo-link clearfix" href="<%= root_url %>"><h1 class="main-logo">ShareDining</h1></a>

  <% if @coordinates != nil %>
    <label for="nav-search" class="nav-search-icon">
      <svg>
        <use xlink:href="#search"></use>
      </svg>
    </label>
    <input id="pac-input" name="location" type="text" class="nav-search" placeholder="Location" aria-label="Location" value="<%= @location %>">
  <% end %>

  <ul class="landing-links">
    <% if user_signed_in? %>
      <li><%= link_to "Messages", conversations_path %></li>
      <li><%= link_to "Help", landing_help_path %></li>
      <li><%= link_to current_user.first_name, dashboard_path %></li>
      <li><%= link_to "Sign out", destroy_user_session_path %></li>
    <% else %>
      <!-- Recipe Book will be a link to the blog -->
      <li><%= link_to "The ShareDining Recipe Book", root_url %></li>
      <li><a href="#" class="nav-login-button">Login</a></li>
      <li><a href="#" class="nav-signup-button">Sign Up</a></li>
    <% end %>
  </ul>
  <a href="<%= new_kitchen_path %>"><button class="transparent-button landing-rent-button">
    Rent Your Kitchen
  </button></a>
</nav>