config/routes.rb
Rails.application.routes.draw do

  root 'landing#user'

  devise_for :users,
             :controllers => {
                sessions: 'sessions', registrations: 'registrations'
             }

  get 'landing/terms_of_use'
  get 'landing/privacy_policy'
  get 'landing/cookie_policy'
  get 'landing/usage_agreement'
  get 'landing/the_kitchen_economy'
  get 'landing/help'

  get 'dashboard' => 'account#show'
  post 'account/payment'

  get 'search/results'
  post 'kitchen/create'

  resources :kitchen do
    match "reservation/new" => "reservation#new", via: :post
    resources :reservation, only: [:create, :show]
    resources :availability, only: :create
  end

  resources :reservation, only: [:edit, :update, :destroy]
  resources :availability, only: [:new, :show, :edit, :update, :destroy]

  scope '/api' do
    scope '/v1' do
      get '/kitchens' => 'kitchen#filter'
    end
  end

  resources :conversations, only: [:index, :destroy] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    member do
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

end

app/models/kitchen.rb
class Kitchen < ActiveRecord::Base

  before_validation :set_token, on: :create
  validates_presence_of :token
  validates_uniqueness_of :token

  validates :title, presence: true
  validates :rental_space, presence: true
  validates :location, presence: true
  validates :price, presence: true
  # don't validate price for testing purposes

  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one :availability, dependent: :destroy

  # Mount photos to kitchen
  mount_uploader :photos, PhotoUploader
  serialize :photos, JSON

  serialize :washing_station, Array
  serialize :food_preparation, Array
  serialize :cookware, Array
  serialize :storage, Array
  serialize :refrigeration, Array
  serialize :ovens_fryers, Array
  serialize :oven_equipment_and_storage, Array
  serialize :baking_and_pastry, Array
  serialize :other_equipment, Array
  serialize :other_amenities, Array

  # auto-fetch coordinates
  geocoded_by :location
  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }

  protected
    def set_token
      self.token = rand(36**8).to_s(36) if self.new_record? and self.token.nil?
    end

end

app/controllers/kitchen_controller.rb
require 'time'

class KitchenController < ApplicationController

  # GET /kitchen/1
  # GET /kitchen/1.json
  def show
    @kitchen = Kitchen.find_by(token: params[:id])
    @censored_address = ('' == @kitchen.location.partition(',').last) ? @kitchen.location : @kitchen.location.partition(',').last
    @reservation = Reservation.new

    @availability = Availability.find_by kitchen_id: @kitchen.id

    # Need ajax call: when user selects date, the time ranges should be the kitchen's available hours
    @day = Date.today.strftime("%A").downcase

    @reviews = Review.where(kitchen_id: @kitchen.id)
    ratings = @reviews.map(&:rating)
    @avg_rating = ratings.inject(0.0) { |sum, el| sum + el } / ratings.length
  end

  # TODO: filter out any information that is not relevant for the results page,
  # TODO: ie SELECT price, name, image[0], lat, long, shared, size
  # GET /api/v1/kitchens
  # Returns a JSON array of relevant kitchens
  # GET parameters are as follows:
  # {Integer} index (required) - the starting index of relevant results to return
  # {Integer} num_results (required) - the number of relevant results to return
  # {String} location (required) - the location string
  # {String} type_of_kitchen - the type of kitchens to be returned. Values may include [any, whole, shared]
  # {String} size_of_kitchen  - the size of the kitchens to be returned. Values may include [any, large, small]
  def filter
    @start_date = params[:start_date]
    @index = params[:index] ? Integer(params[:index]) : nil
    @num_results = params[:num_results] ? Integer(params[:num_results]) : nil
    @location = params[:location]
    @type = params[:type_of_kitchen]
    @sort = params[:sort_kitchens]

    if !@start_date.present? || !@index.present? || !@num_results.present? || !@location.present? || !@type.present? || !@sort.present?
      render :nothing => true, :status => 400
      return
    end

    if @start_date.present?
      day = Time.parse(@start_date).strftime("%A").downcase
      @available_kitchens = Kitchen.joins(:availability).where("#{day} is not null")
      @nearbyKitchens = @available_kitchens.near(@location, 15)
    end

    # Filter between Whole Kitchen and Shared Space
    if @type.present? && @type != 'any'
      if @type == 'whole'
        @nearbyKitchens = @nearbyKitchens.select { |kitchen| kitchen.rental_space == 'Whole Kitchen' }
      elsif @type == 'shared'
        @nearbyKitchens = @nearbyKitchens.select { |kitchen| kitchen.rental_space == 'Shared Space' }
      end
    end

    # Sort orders
    if @sort.present? && @sort != 'best_match'
      if @sort == 'price_low_to_high'
        @nearbyKitchens = @nearbyKitchens.sort_by &:price
      elsif @sort == 'price_high_to_low'
        @nearbyKitchens = (@nearbyKitchens.sort_by &:price).reverse!
      elsif @sort == 'newest_created'
        @nearbyKitchens = (@nearbyKitchens.sort_by &:created_at).reverse!
      end
    end

    # limit number of filtered kitchens to specified num_results
    if @nearbyKitchens.size <= @num_results
      @filtered_kitchens = @nearbyKitchens
    else
      @filtered_kitchens = @nearbyKitchens[@index...@index + @num_results]
    end

    render json: @filtered_kitchens
  end

  # GET /kitchen/new
  def new
    @kitchen = Kitchen.new
    @availability = Availability.new
  end

  # GET /kitchen/1/edit
  def edit
  end

  # POST /kitchen
  # POST /kitchen.json
  def create
    @kitchen = Kitchen.new(kitchen_params)
    params[:whole_kitchen] == "1" ? (@kitchen.rental_space = "Whole Kitchen") : (@kitchen.rental_space = "Shared Space")

    @availability = Availability.new

    if @kitchen.save
      @availability.kitchen_id = @kitchen.id

      parse_availability
      @availability.save

      @photos = @kitchen.photos

      UserMailer.new_kitchen_email(User.find_by(id: @kitchen.user_id), @kitchen).deliver_now

      redirect_to kitchen_path(@kitchen.token)
      flash[:notice] = 'Kitchen was successfully added.'
    else
      respond_to do |format|
        if !params[:kitchen][:title].present?
          flash[:notice]='Error: Kitchen title is required'
	elsif !params[:kitchen][:description].present?
	  flash[:notice]='Error: Kitchen description is required'
 	elsif !params[:kitchen][:location].present?
	  flash[:notice]='Error: Kitchen location is required'
      	elsif !params[:kitchen][:price].present?
	  flash[:notice]='Error: Kitchen price is required'
	else
          flash[:notice] = 'Error: Kitchen was not successfully added.'
        end
        format.html { render action: 'new' }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitchen/1
  # PATCH/PUT /kitchen/1.json
  def update
    # respond_to do |format|
  #   if @kitchen.update_attributes(post_params)
    #     format.html { redirect_to @kitchen, notice: 'Kitchen was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: 'edit' }
    #     format.json { render json: @kitchen.errors, status :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /kitchen/1
  # DELETE /kitchen/1.json
  def destroy
  end

  private
    def kitchen_params
      params.require(:kitchen).permit(:user_id, :title, :description, :location, :rental_space,
                                      :kitchen_rules_and_instructions, :additional_details, :price,
                                      :cancellation_policy,
                                      { washing_station: [] }, { food_preparation: [] },
                                      { food_preparation: [] }, { cookware: [] }, { storage: [] },
                                      { refrigeration: [] }, { ovens_fryers: [] },
                                      { oven_equipment_and_storage: [] }, { baking_and_pastry: [] },
                                      { other_equipment: [] }, { other_amenities: [] }, { photos: [] }
                                      )
    end

    def parse_availability
      # Assigns availability attribute in format such as [3, 6], both digits are strings
      @sunday_availability = params[:sunday_availability]
      @monday_availability = params[:monday_availability]
      @tuesday_availability = params[:tuesday_availability]
      @wednesday_availability = params[:wednesday_availability]
      @thursday_availability = params[:thursday_availability]
      @friday_availability = params[:friday_availability]
      @saturday_availability = params[:saturday_availability]

      @sunday_time = @sunday_availability.split(',')
      @availability.sunday = (@sunday_time[0] == '0' && @sunday_time[1] == '0') ? nil : [@sunday_time[0], @sunday_time[1]]

      @monday_time = @monday_availability.split(',')
      @availability.monday = (@monday_time[0] == '0' && @monday_time[1] == '0') ? nil : [@monday_time[0], @monday_time[1]]

      @tuesday_time = @tuesday_availability.split(',')
      @availability.tuesday = (@tuesday_time[0] == '0' && @tuesday_time[1] == '0') ? nil : [@tuesday_time[0], @tuesday_time[1]]

      @wednesday_time = @wednesday_availability.split(',')
      @availability.wednesday = (@wednesday_time[0] == '0' && @wednesday_time[1] == '0') ? nil : [@wednesday_time[0], @wednesday_time[1]]

      @thursday_time = @thursday_availability.split(',')
      @availability.thursday = (@thursday_time[0] == '0' && @thursday_time[1] == '0') ? nil : [@thursday_time[0], @thursday_time[1]]

      @friday_time = @friday_availability.split(',')
      @availability.friday = (@friday_time[0] == '0' && @friday_time[1] == '0') ? nil : [@friday_time[0], @friday_time[1]]

      @saturday_time = @saturday_availability.split(',')
      @availability.saturday = (@saturday_time[0] == '0' && @saturday_time[1] == '0') ? nil : [@saturday_time[0], @saturday_time[1]]
    end

end

app/helpers/kitchen_helper.rb
module KitchenHelper  
end

app/views/kitchen/_multiple_reservation_modal.html.erb
<div class="multiple-reservation-modal modal" role="dialog" aria-labelledby="reservation-modal-title" aria-describedby="reservation-modal-description">
  <h1 id="reservation-modal-title" class="modal-title">Recurring Reservation</h1>
  <h2 id="reservation-modal-description" class="modal-tagline">Book kitchens regularly</h2>
  <br>
  <%= form_for @reservation, url: kitchen_reservation_new_path(@kitchen, @reservation), html: {method: :post, class: "listing-dates-form"} do |f| %>
    <%= f.hidden_field :multiple, value: true %>
    <label class="listing-date-label" for="start_date">Start Date</label>
    <%= f.date_field :start_date, value: Date.today, class: "listing-start-date" %>
    <br/><br>
    <label class="listing-date-label" for="start_date">End Date</label>
    <%= f.date_field :end_date, value: Date.today + 7, class: "listing-start-date" %>
    <br/><br>
    <ul class="day-availability-list">
      <li class="day-availability-list-element">
        <h2>Sunday</h2>
        <% if @availability.sunday != [] %>
          <%= f.time_select :sunday_start_time, minute_step: 30, start_hour: @availability.sunday[0].to_i, end_hour: @availability.sunday[1].to_i, time_separator: ':' %> to
          <%= f.time_select :sunday_end_time, minute_step: 30, start_hour: @availability.sunday[0].to_i, end_hour: @availability.sunday[1].to_i, time_separator: ':' %>
        <% else %>
          No times available
        <% end %>
      </li>
      <br/>

      <li class="day-availability-list-element">
        <h2>Monday</h2>
        <% if @availability.monday != [] %>
          <%= f.time_select :monday_start_time, minute_step: 30, start_hour: @availability.monday[0].to_i, end_hour: @availability.monday[1].to_i, time_separator: ':' %> to
          <%= f.time_select :monday_end_time, minute_step: 30, start_hour: @availability.monday[0].to_i, end_hour: @availability.monday[1].to_i, time_separator: ':' %>
        <% else %>
          No times available
        <% end %>
      </li>
      <br/>

      <li class="day-availability-list-element">
        <h2>Tuesday</h2>
        <% if @availability.tuesday != [] %>
          <%= f.time_select :tuesday_start_time, minute_step: 30, start_hour: @availability.tuesday[0].to_i, end_hour: @availability.tuesday[1].to_i, time_separator: ':' %> to
          <%= f.time_select :tuesday_end_time, minute_step: 30, start_hour: @availability.tuesday[0].to_i, end_hour: @availability.tuesday[1].to_i, time_separator: ':' %>
        <% else %>
          No times available
        <% end %>
      </li>
      <br/>

      <li class="day-availability-list-element">
        <h2>Wednesday</h2>
        <% if @availability.wednesday != [] %>
          <%= f.time_select :wednesday_start_time, minute_step: 30, start_hour: @availability.wednesday[0].to_i, end_hour: @availability.wednesday[1].to_i, time_separator: ':' %> to
          <%= f.time_select :wednesday_end_time, minute_step: 30, start_hour: @availability.wednesday[0].to_i, end_hour: @availability.wednesday[1].to_i, time_separator: ':' %>
        <% else %>
          No times available
        <% end %>
      </li>
      <br/>

      <li class="day-availability-list-element">
        <h2>Thursday</h2>
        <% if @availability.thursday != [] %>
          <%= f.time_select :thursday_start_time, minute_step: 30, start_hour: @availability.thursday[0].to_i, end_hour: @availability.thursday[1].to_i, time_separator: ':' %> to
          <%= f.time_select :thursday_end_time, minute_step: 30, start_hour: @availability.thursday[0].to_i, end_hour: @availability.thursday[1].to_i, time_separator: ':' %>
        <% else %>
          No times available
        <% end %>
      </li>
      <br/>

      <li class="day-availability-list-element">
        <h2>Friday</h2>
        <% if @availability.friday != [] %>
          <%= f.time_select :friday_start_time, minute_step: 30, start_hour: @availability.friday[0].to_i, end_hour: @availability.friday[1].to_i, time_separator: ':' %> to
          <%= f.time_select :friday_end_time, minute_step: 30, start_hour: @availability.friday[0].to_i, end_hour: @availability.friday[1].to_i, time_separator: ':' %>
        <% else %>
          No times available
        <% end %>
      </li>
      <br/>

      <li class="day-availability-list-element">
        <h2>Saturday</h2>
        <% if @availability.saturday != [] %>
          <%= f.time_select :saturday_start_time, minute_step: 30, start_hour: @availability.saturday[0].to_i, end_hour: @availability.saturday[1].to_i, time_separator: ':' %> to
          <%= f.time_select :saturday_end_time, minute_step: 30, start_hour: @availability.saturday[0].to_i, end_hour: @availability.saturday[1].to_i, time_separator: ':' %>
        <% else %>
          No times available
        <% end %>
      </li>
    </ul>
    <%= f.submit "Request Kitchen" %>
  <% end %>
</div>

app/views/kitchen/_single_reservation_modal.html.erb
<div class="single-reservation-modal modal" role="dialog" aria-labelledby="reservation-modal-title" aria-describedby="reservation-modal-description">
  <h1 id="reservation-modal-title" class="modal-title">Single Reservation</h1>
  <h2 id="reservation-modal-description" class="modal-tagline">Book a kitchen</h2>
  <br/>
  <%= form_for @reservation, url: kitchen_reservation_new_path(@kitchen, @reservation), html: {method: :post, class: "listing-dates-form"} do |f| %>
    <%= f.hidden_field :multiple, value: false %>
    <label class="listing-date-label" for="start_date">Date</label>
    <%= f.date_field :start_date, value: Date.today, class: "listing-start-date" %>
    <!-- TODO: load only available hours -->
    <br/><br>
    <%= f.label :start_time %>
    <%= f.time_select :start_time, minute_step: 30, start_hour: @availability[@day][0].to_i, end_hour: @availability[@day][1].to_i, time_separator: ':' %>
    <br/><br>
    <%= f.label :end_time %>
    <%= f.time_select :end_time, minute_step: 30, start_hour: @availability[@day][0].to_i, end_hour: @availability[@day][1].to_i, time_separator: ':' %>
    <%= f.submit "Request Kitchen" %>
  <% end %>
</div>

app/views/kitchen/show.html.erb
<body class="kitchen-listing-body" data-js="kitchen-show">

<section class="modal-overlay">
  <%= render("multiple_reservation_modal") %>
  <%= render("single_reservation_modal") %>
</section>

<%= render("shared/menu") %>

<div class="listing-container">
  <section class="listing-head-container clearfix">
    <h2 class="listing-title"><%= @kitchen.title %></h2>
    <ul class="listing-details-list">
      <li><%= @censored_address %></li>
      <!-- <li>2 Reviews</li> -->
    </ul>
  </section>

  <section class="listing-date-container clearfix">
    <%= form_for @reservation, url: kitchen_reservation_new_path(@kitchen, @reservation), html: {method: :post, class: "listing-dates-form"} do |f| %>
      <%= f.radio_button :multiple, 'Single Reservation', class: 'single-reservation-button' %>
      <%= f.label :multiple, 'Single Reservation', value: false %>
      <%= f.radio_button :multiple, 'Multiple Reservations', class: 'multiple-reservation-button' %>
      <%= f.label :multiple, 'Multiple Reservations', value: true %>

      <!-- <div class="listing-dates-form-field"> -->
        <!-- <label class="listing-date-label" for="start_date">Date</label> -->
        <%# f.date_field :start_date, value: Date.today, class: "listing-start-date" %>
        <!-- TODO: load only available hours -->
        <%# f.time_select :start_time, minute_step: 30, start_hour: @availability[@day][0].to_i, end_hour: @availability[@day][1].to_i, time_separator: ':' %>
        <%# f.time_select :end_time, minute_step: 30, start_hour: @availability[@day][0].to_i, end_hour: @availability[@day][1].to_i, time_separator: ':' %>
      <!-- </div> -->

    <% end %>

    <div class="listing-price-container">
      <!--<span class="listing-price">-->
        <!--<span class="price-math">£<%= @kitchen.price * 1.2 %>/hr * 3 hours =</span>-->
        <!--&lt;!&ndash; need Ajax to update math display &ndash;&gt;-->
        <!--<span class="listing-total-price">$920</span>-->
      <!--</span>-->
      <!-- <button form="new_reservation" type="submit" class="transparent-button listing-book-button">Request Kitchen</button> -->
      <%= link_to 'Message Owner', new_message_path(:kitchen_owner => @kitchen.user_id), class: "transparent-button listing-book-button"%>
    </div>
  </section>

  <section class="listing-images-container slider-container" role="region" aria-label="Kitchen Images">
    <button class="prev-button">Previous Slide</button>
    <button class="next-button">Next Slide</button>
    <ul id="listing-images" class="slider-list">
      <!--TODO: remove if else block for production, this is simply for testing kitchens that don't have images-->
      <% if @kitchen.photos.present? %>
        <% @kitchen.photos.each do |photo| %>
            <li class="slider-list-element">
              <%= image_tag photo, class: 'listing-image' %>
            </li>
        <% end %>
      <% else %>
        <li class="slider-list-element">
          <%= image_tag 'sampleKitchens/1.jpg', class: 'listing-image' %>
        </li>
        <li class="slider-list-element">
          <%= image_tag 'sampleKitchens/2.jpg', class: 'listing-image' %>
        </li>
        <li class="slider-list-element">
          <%= image_tag 'sampleKitchens/3.jpeg', class: 'listing-image' %>
        </li>
        <li class="slider-list-element">
          <%= image_tag 'sampleKitchens/4.jpeg', class: 'listing-image' %>
        </li>
      <% end %>
    </ul>
    <ul class="breadcrumb-list"></ul>
  </section>

  <section class="listing-details-container">
    <div class="listing-description">
      <h2 class="listing-details-heading">Description</h2>
      <p>
        <%= @kitchen.description %>
      </p>
    </div>

    <div class="listing-features clearfix">
      <% if @kitchen.washing_station.present? %>
          <div class="listing-inventory-section-container">
            <h2 class="listing-features-heading">Washing Station</h2>
            <ul class="listing-features-list">
              <% @kitchen.washing_station.each do |washing_station| %>
                  <li><%= washing_station %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <% if @kitchen.food_preparation.present? %>
          <div class="listing-inventory-section-container">
            <h2 class="listing-features-heading">Food Preparation</h2>
            <ul class="listing-features-list">
              <% @kitchen.food_preparation.each do |food_preparation| %>
                  <li><%= food_preparation %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <% if @kitchen.cookware.present? %>
          <div class="listing-inventory-section-container">
            <h2 class="listing-features-heading">Cookware</h2>
            <ul class="listing-features-list">
              <% @kitchen.cookware.each do |cookware| %>
                  <li><%= cookware %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <% if @kitchen.storage.present? %>
          <div class="listing-inventory-section-container">
            <h2 class="listing-features-heading">Storage</h2>
            <ul class="listing-features-list">
              <% @kitchen.storage.each do |storage| %>
                  <li><%= storage %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <% if @kitchen.refrigeration.present? %>
          <div class="listing-inventory-section-container">
            <h2 class="listing-features-heading">Refrigeration</h2>
            <ul class="listing-features-list">
              <% @kitchen.refrigeration.each do |refrigeration| %>
                  <li><%= refrigeration %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <% if @kitchen.ovens_fryers.present? %>
          <div class="listing-inventory-section-container">
            <h2 class="listing-features-heading">Ovens/Fryers</h2>
            <ul class="listing-features-list">
              <% @kitchen.ovens_fryers.each do |ovens_fryers| %>
                  <li><%= ovens_fryers %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <% if @kitchen.oven_equipment_and_storage.present? %>
          <div class="listing-inventory-section-container">
            <h2 class="listing-features-heading">Oven Equipment &amp; Storage</h2>
            <ul class="listing-features-list">
              <% @kitchen.oven_equipment_and_storage.each do |oven_equipment_and_storage| %>
                  <li><%= oven_equipment_and_storage %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <% if @kitchen.baking_and_pastry.present? %>
          <div class="listing-inventory-section-container">
            <h2 class="listing-features-heading">Baking &amp; Pastry</h2>
            <ul class="listing-features-list">
              <% @kitchen.baking_and_pastry.each do |baking_and_pastry| %>
                  <li><%= baking_and_pastry %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <% if @kitchen.other_equipment.present? %>
          <div class="listing-inventory-section-container">
            <h2 class="listing-features-heading">Other Equipment</h2>
            <ul class="listing-features-list">
              <% @kitchen.other_equipment.each do |other_equipment| %>
                  <li><%= other_equipment %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <% if @kitchen.other_amenities.present? %>
          <div class="listing-inventory-section-container">
            <h2 class="listing-features-heading">Other Amenities</h2>
            <ul class="listing-features-list">
              <% @kitchen.other_amenities.each do |other_amenities| %>
                  <li><%= other_amenities %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

    </div>
  </section>

  <section class="listing-review-container">
    <div class="listing-review-heading">
      <% if @reviews.length == 1 %>
        <%= @reviews.length %> Review (<%= @avg_rating %> stars)
      <% else %>
        <%= @reviews.length %> Reviews (<%= @avg_rating %> stars)
      <% end %>
    </div>

    <ul class="listing-review-list">
      <% if @reviews.length == 0 %>
        No reviews yet.
      <% else %>
        <% @reviews.each do |review| %>
          <li class="listing-review-name">
            <%= review.user.first_name %>
            <br/>
            <%= review.created_at.strftime("%B %d") %>
          </li>
          <li class="listing-review-content">
            <%= review.comment %>
          </li>
          <hr/>
        <% end %>
      <% end %>
    </ul>
  </section>
</div>

<%= render("shared/footer") %>
</body>